### Verbo GET – listar todos
GET http://localhost:8000/cliente/ HTTP/1.1
### Verbo GET – listar um
GET http://localhost:8000/cliente/1 HTTP/1.1
### Verbo POST – adicionar
#thiago avila
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
content-type: application/json

{
"nome" : "Abc da Silva",
"cpf" : "01923874656",
"telefone" : "49988234567",
"compra_fiado" : 21,
"dia_fiado" : 20,
"senha" : "bolinhas"
}
### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/1 HTTP/1.1
content-type: application/json

{
"nome" : "Abc da Silva",
"cpf" : "01923874656",
"telefone" : "49458234567",
"compra_fiado" : 21,
"dia_fiado" : 22,
"senha" : "bolinhas"
}
### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/1 HTTP/1.1